In [5]:
import pandas as pd

# Read the CSV file
csv_data = pd.read_csv("NETS_Small.csv")

# Read the TXT file with specified encoding
txt_data = pd.read_csv("Moves2020_CA(WithAddressInfo).txt", delimiter="\t", encoding='latin1')

# Combine the data frames (row-wise or column-wise based on your needs)
combined_data = pd.concat([csv_data, txt_data], axis=0)  # For stacking rows
# combined_data = pd.concat([csv_data, txt_data], axis=1)  # For merging columns

# Export combined data to a new CSV file
combined_data.to_csv("Combined_Data.csv", index=False)

/var/folders/kc/8tx_gqt13nz9mf5s5n2c_jy40000gn/T/ipykernel_62922/3165613173.py:4: DtypeWarning: Columns (22,23) have mixed types. Specify dtype option on import or set low_memory=False.
  csv_data = pd.read_csv("NETS_Small.csv")

In [6]:
combined_data

,DunsNumber,Company,TradeName,HQCompany,HQTradeName,HQDuns,ZipCode,CityCode,City,FipsCounty,...,MoveSalesC,MoveOften,Active,OriginLatitude,OriginLongitude,OriginLevelCode,DestLatitude,DestLongitude,DestLevelCode,Distance
0,73249872.0,UNITED CHURCH OF CHRIST BOARD,OFFICE OF GENERAL MINISTRIES,UNITED CHURCH OF CHRIST BOARD,OFFICE OF GENERAL MINISTRIES,73249872.0,44115.0,391661.0,CLEVELAND,39035.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1067115.0,AVEDIS ZILDJIAN CO,NaN,AVEDIS ZILDJIAN CO,NaN,1067115.0,2061.0,255964.0,NORWELL,25023.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,73299026.0,NEW YORK CITY OF,NaN,NEW YORK STATE OF,NY STATE OMIG,41002973.0,10007.0,364997.0,NEW YORK,36061.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,100032101.0,MALDEN SCHOOL DISTRICT,MALDEN PUBLIC SCHOOLS,MALDEN SCHOOL DISTRICT,MALDEN PUBLIC SCHOOLS,100032101.0,2148.0,254326.0,MALDEN,25017.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,791139595.0,FRIENDS MTING-LA JOLLA-QUAKERS,NaN,FRIENDS MTING-LA JOLLA-QUAKERS,NaN,791139595.0,92037.0,64223.0,LA JOLLA,6073.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1072080,969998470.0,TYLER OLD TROUP HIGHWAY LLC ...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3.0,No,Yes,32.3025,95.2653,D,33.0458,117.2954,D,1281.322
1072081,969976492.0,GRASSROTS ENVMTL CNSORTIUM LLC ...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3.0,No,No,38.6104,121.3876,D,38.4464,121.3252,D,11.835
1072082,969992429.0,MALCOLM PIRNIE INC ...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3.0,No,No,37.8110,122.2629,D,37.8373,122.3002,D,2.732
1072083,969912542.0,JBG INTERNATIONAL INC ...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3.0,No,No,37.7897,122.4020,D,37.7914,122.3985,D,0.225
1072084,969913078.0,PAINTING USA ...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3.0,No,No,37.7721,122.4153,D,37.2015,121.8494,D,50.222